# ==============================================================
# 1. EL SEÑUELO
# ==============================================================
spring.datasource.url=jdbc:sqlserver://26.141.229.180:1433;databaseName=db_econo;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=123

# ==============================================================
# 2. TUS CONEXIONES REALES
# ==============================================================
# Base de datos 1: Econo
spring.datasource.econo.jdbc-url=jdbc:sqlserver://26.141.229.180:1433;databaseName=db_econo;encrypt=true;trustServerCertificate=true;
spring.datasource.econo.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.econo.username=sa
spring.datasource.econo.password=123

# Base de datos 2: Conexion Digital
spring.datasource.conexion.jdbc-url=jdbc:sqlserver://26.141.229.180:1433;databaseName=db_conexiondigital;encrypt=true;trustServerCertificate=true;
spring.datasource.conexion.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.conexion.username=sa
spring.datasource.conexion.password=123

# ==============================================================
# 3. CONFIGURACIÓN DE HIBERNATE/JPA
# ==============================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl